# Workflow to build, Test and Upload Coverage to Sonar
# @author rouroy
# @since 2023.09.22

name: Artifactory Publish 🚀

inputs:
  code-tag:
    description: 'Code tag'
    required: true
  working-directory:
    description: 'Set working directory if not in project root dir. Composite actions runs in root instead of current working directory'
    required: true


runs:
  using: composite
  steps:
    - name: Setup Gradle Build Action
      shell: bash
      run: |
        gradle \
        artifactoryPublish \
        -PcmdOverwriteVer=${{ inputs.code-tag }} \
        -x test
