name: Build & Test 💣

on:
  push:
    paths:
      - sync-service/

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-sync-service
  cancel-in-progress: true

jobs:
  sync-service-ci:
    uses: ./.github/workflows/gradle-build.yml
    with:
      working-directory: 'sync-service'
    secrets: inherit
