/// Strongly-typed Rust structs for all Claude structured output responses.
///
/// Every Claude API call returns one of these types — never freeform text.
/// See CLAUDE.md → "Structured Output, Not Freeform Generation" for the schemas.
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Assignment generation output
// ---------------------------------------------------------------------------

/// Interaction modality for multi-modal assignments.
///
/// Controls the UI component used to present the assignment.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AssignmentModality {
    Text,
    VisualInteractive,
    Sequencing,
    Drawing,
    AudioEnhanced,
    TeachBack,
}

/// A structured assignment generated by Claude.
///
/// `correctAnswer` and `acceptableAnswers` are **verified programmatically by the
/// backend** before the assignment is shown to the child. Claude can be wrong;
/// the backend catches it.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GeneratedAssignment {
    /// Assignment type (e.g. `"sequence-puzzle"`, `"deductive-reasoning"`).
    pub assignment_type: String,
    /// Skill ID this assignment targets (must match a valid skill in `skill-tree.json`).
    pub skill: String,
    /// Difficulty level (1–10 scale).
    pub difficulty: u32,
    /// Theme applied to this assignment (e.g. `"dinosaurs"`, `"space"`).
    pub theme: String,
    /// The problem text shown to the child.
    pub prompt: String,
    /// The single canonical correct answer (may be any JSON value: number, string, array).
    pub correct_answer: serde_json::Value,
    /// Answers the backend should also accept as correct (aliases, alternate formats).
    pub acceptable_answers: Vec<serde_json::Value>,
    /// Scaffolded hints from vague (index 0) to specific (last index). Exactly 3 levels.
    pub hints: Vec<String>,
    /// Explanation of *why* the answer is correct — used in post-answer feedback.
    pub explanation: String,
    /// Optional interaction modality. Defaults to text-based if absent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modality: Option<AssignmentModality>,
    /// Structured verification data for backend answer checking.
    ///
    /// For `sequence-puzzle`: `{"terms": [2, 4, 8], "sequenceType": "geometric"}`
    /// For `deductive-reasoning`: `{"premises": ["If A then B", "A is true"], "conclusion": "B"}`
    /// For `pattern-matching`: omitted — `acceptableAnswers` is used directly.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_data: Option<serde_json::Value>,
}

// ---------------------------------------------------------------------------
// Response evaluation output
// ---------------------------------------------------------------------------

/// Claude's confidence in its evaluation of a free-form answer.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum EvaluationConfidence {
    High,
    Medium,
    Low,
}

/// Behavioral signals Claude observed while evaluating a child's response.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ObservedBehavioralSignals {
    /// Whether the child appeared to self-correct before submitting.
    pub self_correction_detected: bool,
    /// Whether the child used a hint before answering.
    pub hint_used: bool,
    /// Whether the response time suggests the child struggled (heuristic).
    pub response_suggests_struggle: bool,
    /// Optional free-text note from Claude about the child's reasoning approach.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_note: Option<String>,
}

/// Structured evaluation returned by Claude for a child's response.
///
/// **Important**: `correct` is always cross-checked against the backend's own
/// answer verification. Claude's assessment here is used for tone and
/// explanation, not for authoritative correctness judgment.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EvaluationResult {
    /// Whether Claude assessed the response as correct.
    /// The backend must still verify this independently.
    pub correct: bool,
    /// Claude's confidence in this evaluation.
    pub confidence: EvaluationConfidence,
    /// Growth-mindset, encouraging feedback text for the child.
    /// Must follow the feedback guardrails — no discouraging language.
    pub feedback: String,
    /// Explanation of the correct answer and why the child's answer was
    /// correct or what to look for if it was not.
    pub explanation: String,
    /// Behavioral signals observed during evaluation.
    pub behavioral_signals: ObservedBehavioralSignals,
}

// ---------------------------------------------------------------------------
// Session narrative output
// ---------------------------------------------------------------------------

/// Difficulty adjustment recommendation for the next session.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum DifficultyAdjustment {
    Increase,
    Maintain,
    Decrease,
}

/// Structured session narrative generated by Claude after a session ends.
///
/// The **backend** uses this as structured input to write the session markdown
/// file on disk. Claude provides the content; the backend is the file author.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionNarrative {
    /// Behavioral observations for the "Behavioral Observations" section of the session markdown.
    pub behavioral_observations: String,
    /// Continuity notes for the "Continuity Notes" section — what to remember for next session.
    pub continuity_notes: String,
    /// Recommended skill focus areas for the next session (list of skill IDs).
    pub recommended_focus_areas: Vec<String>,
    /// Recommended difficulty adjustment for the next session.
    pub difficulty_adjustment: DifficultyAdjustment,
    /// Optional flag indicating whether this session warrants parent review
    /// (e.g., a low-confidence evaluation was made).
    #[serde(default)]
    pub flag_for_parent_review: bool,
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generated_assignment_serde_round_trip() {
        let a = GeneratedAssignment {
            assignment_type: "sequence-puzzle".to_string(),
            skill: "pattern-recognition".to_string(),
            difficulty: 4,
            theme: "dinosaurs".to_string(),
            prompt: "A T-Rex takes 2 steps, then 4, then 8. How many steps next?".to_string(),
            correct_answer: serde_json::json!(16),
            acceptable_answers: vec![
                serde_json::json!(16),
                serde_json::json!("16"),
                serde_json::json!("sixteen"),
            ],
            hints: vec![
                "Look at how the number changes each time...".to_string(),
                "Each time, the number doubles!".to_string(),
                "8 × 2 = ?".to_string(),
            ],
            explanation: "Each step count doubles: 2→4→8→16. This is a geometric sequence!"
                .to_string(),
            modality: None,
            verification_data: Some(
                serde_json::json!({"terms": [2, 4, 8], "sequenceType": "geometric"}),
            ),
        };
        let json = serde_json::to_string(&a).expect("serialize");
        let restored: GeneratedAssignment = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(a, restored);
    }

    #[test]
    fn test_generated_assignment_camel_case_fields() {
        let a = GeneratedAssignment {
            assignment_type: "sequence-puzzle".to_string(),
            skill: "pattern-recognition".to_string(),
            difficulty: 4,
            theme: "space".to_string(),
            prompt: "What comes next?".to_string(),
            correct_answer: serde_json::json!(32),
            acceptable_answers: vec![],
            hints: vec![
                "hint1".to_string(),
                "hint2".to_string(),
                "hint3".to_string(),
            ],
            explanation: "explanation".to_string(),
            modality: Some(AssignmentModality::VisualInteractive),
            verification_data: None,
        };
        let json = serde_json::to_string(&a).expect("serialize");
        assert!(json.contains("\"assignmentType\""));
        assert!(json.contains("\"correctAnswer\""));
        assert!(json.contains("\"acceptableAnswers\""));
        assert!(json.contains("\"visual-interactive\""));
    }

    #[test]
    fn test_evaluation_result_serde_round_trip() {
        let e = EvaluationResult {
            correct: true,
            confidence: EvaluationConfidence::High,
            feedback: "Great thinking! You spotted the doubling pattern right away!".to_string(),
            explanation: "Each number doubles: 2→4→8→16. That's geometric growth.".to_string(),
            behavioral_signals: ObservedBehavioralSignals {
                self_correction_detected: false,
                hint_used: false,
                response_suggests_struggle: false,
                reasoning_note: Some("Answered quickly and correctly".to_string()),
            },
        };
        let json = serde_json::to_string(&e).expect("serialize");
        let restored: EvaluationResult = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(e, restored);
    }

    #[test]
    fn test_evaluation_confidence_kebab_case() {
        assert_eq!(
            serde_json::to_string(&EvaluationConfidence::High).unwrap(),
            "\"high\""
        );
        assert_eq!(
            serde_json::to_string(&EvaluationConfidence::Medium).unwrap(),
            "\"medium\""
        );
        assert_eq!(
            serde_json::to_string(&EvaluationConfidence::Low).unwrap(),
            "\"low\""
        );
    }

    #[test]
    fn test_session_narrative_serde_round_trip() {
        let n = SessionNarrative {
            behavioral_observations: "Child stayed engaged throughout the session.".to_string(),
            continuity_notes: "Ready to try 3-step sequential problems next session.".to_string(),
            recommended_focus_areas: vec!["sequential-logic".to_string()],
            difficulty_adjustment: DifficultyAdjustment::Increase,
            flag_for_parent_review: false,
        };
        let json = serde_json::to_string(&n).expect("serialize");
        let restored: SessionNarrative = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(n, restored);
    }

    #[test]
    fn test_difficulty_adjustment_kebab_case() {
        assert_eq!(
            serde_json::to_string(&DifficultyAdjustment::Increase).unwrap(),
            "\"increase\""
        );
        assert_eq!(
            serde_json::to_string(&DifficultyAdjustment::Maintain).unwrap(),
            "\"maintain\""
        );
        assert_eq!(
            serde_json::to_string(&DifficultyAdjustment::Decrease).unwrap(),
            "\"decrease\""
        );
    }

    #[test]
    fn test_session_narrative_flag_defaults_false() {
        let json = r#"{
            "behavioralObservations": "...",
            "continuityNotes": "...",
            "recommendedFocusAreas": [],
            "difficultyAdjustment": "maintain"
        }"#;
        let n: SessionNarrative = serde_json::from_str(json).expect("deserialize");
        assert!(!n.flag_for_parent_review);
    }
}
